# Generated by Django 3.1 on 2020-08-30 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200830_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='me',
        ),
        migrations.AddField(
            model_name='friends',
            name='me',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friends_me', to='users.user'),
            preserve_default=False,
        ),
    ]
