# Generated by Django 3.1 on 2020-08-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200830_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
