# Generated by Django 3.1 on 2020-08-30 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='me',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_me', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
